feat: css-modules
cle-uv/create-react-app pull request #12
Opened 2020-06-04 10:58 UTC by cle-uv

close #11

2020-06-04 22:53 UTC, piro0919 requested changes
@cle-uv 
以下追加でご対応お願いしますー 👍 

- class名はlower camel caseで統一する
- .module.scssファイルのファイル名はstyle.module.scssで統一する

2020-06-04 22:54 UTC, piro0919 commented
@cle-uv 
あと、気づかないうちにcomponentフォルダが生成されていますが、複数形のほうが好みですね
issue を立てて頂いて、このPRより先に対応しましょうか 👍

2020-06-05 02:01 UTC, cle-uv commented
#13 対応後にrebaseしてからPR出し直すのでcloseします

2020-06-05 04:11 UTC, piro0919 requested changes
ご確認よろしくお願いしますー 🙇

2020-06-05 04:11 UTC, piro0919 commented on src/App.tsx
> +import styles from './styles.module.scss';
[must]
style.module.scss で統一したいです 👍

2020-06-05 04:11 UTC, piro0919 commented on src/components/atoms/button/Button.js
> +import styles from './styles.module.scss'; // Import css modules stylesheet as styles
[must]
style.module.scss で統一したいです 👍

2020-06-05 04:18 UTC, cle-uv commented on src/App.tsx
> +import styles from './styles.module.scss';
失礼しました！修正しました！

2020-06-05 04:18 UTC, cle-uv commented on src/components/atoms/button/Button.js
> +import styles from './styles.module.scss'; // Import css modules stylesheet as styles
こちらも修正！

2020-06-05 04:26 UTC, piro0919 commented
@yut-kameda 
ちょー細かいですが、コミットメッセージはrefactorではなくfixのほうが良かったですね 👍

2020-06-05 04:27 UTC, piro0919 approved these changes
LGTM!!!!!!!!!!素晴らしい 👍👍👍

2020-06-05 04:34 UTC, cle-uv commented
> コミットメッセージはrefactorではなくfixのほうが良かったですね

なるほど。不備の修正なのでfixですね、了解です！ 😄

2020-06-05 04:35 UTC, merged