feat: add react-router-dom
cle-uv/create-react-app pull request #23
Opened 2020-06-07 01:45 UTC by cle-uv

close #22

2020-06-07 02:07 UTC, piro0919 requested changes

2020-06-07 02:07 UTC, piro0919 commented on package.json
> +    "extends": [
[must]
こちらのフォーマットが修正されていますが、なぜでしょうかー

2020-06-07 02:07 UTC, piro0919 commented on package.json
> +    "react-router-dom": "^5.2.0",
[must]
何度も指摘していますが、バージョンは固定してインストールしましょう 💢

2020-06-07 02:41 UTC, cle-uv commented on package.json
> +    "react-router-dom": "^5.2.0",
@piro0919 
失礼しました！ #24  こちらでnpmrc導入して対策します！

2020-06-07 02:42 UTC, cle-uv commented on package.json
> +    "extends": [
@piro0919 
yarn addした際に自動で整形されていたようです。
今回のissue内容に関係ない部分なので、戻した方が良いでしょうか。

2020-06-07 02:43 UTC, piro0919 commented on package.json
> +    "extends": [
@cle-uv 
yarn addでpackage.jsonが整形されることはないですね 🙅‍♂️ 
他の要因だと思います、もう少し原因を調べてくださいー

2020-06-07 02:46 UTC, piro0919 commented on package.json
> +    "react-router-dom": "^5.2.0",
@cle-uv 
追記しましたー
rel https://github.com/cle-uv/create-react-app/issues/24#issuecomment-640148030

2020-06-07 03:14 UTC, cle-uv commented on package.json
> +    "extends": [
@piro0919 
npm initしただけの環境で、npm installでもyarn addでも試してみたのですが、
どちらも修正されてしまい、他の要因が思いつかないです。

なにが原因になりそうな部分あれば教えていただきたいです 🙇

2020-06-07 03:18 UTC, piro0919 commented on package.json
> +    "extends": [
@cle-uv 
vscodeの設定かパッケージが怪しそうです
保存時にフォーマッタをかける設定が入っているとか？

2020-06-07 03:19 UTC, cle-uv commented on package.json
> +    "extends": [
commitlintの設定を追加した時に、vscodeで保存時にprettierでフォーマットする設定がoffだったのも原因のひとつなので、vscodeで保存時にフォーマットするようにしました。

2020-06-07 03:22 UTC, cle-uv commented on package.json
> +    "extends": [
@piro0919 
かと思ってvscode閉じてターミナルだけで実行したのですが、自動修正されてしまいました。。

2020-06-07 03:28 UTC, piro0919 commented on package.json
> +    "extends": [
@cle-uv 
なるほど
package.jsonにフォーマットがかかるタイミングについて調べてみてくださいな、こちらでも調べますー
issue化するほどでもないと思うのでissue化は不要です 👍

2020-06-07 03:40 UTC, piro0919 commented on package.json
> +    "extends": [
@cle-uv 
ちょっとよくわからないので、今回は保留でー 🙇

2020-06-07 03:41 UTC, cle-uv commented on package.json
> +    "extends": [
@piro0919 
了解です。修正された部分はこのPRでは戻した方がいいですか？

2020-06-07 03:44 UTC, piro0919 commented on package.json
> +    "extends": [
@cle-uv 
亀田さんの言葉を信じて、このままでいきましょうー
ただ、こういったPRのフォーカスから外れた修正については、随時詳しい内容をコメントして頂けると、レビューする側としてはひじょーに助かります 👍

2020-06-07 03:51 UTC, cle-uv commented on package.json
> +    "extends": [
@piro0919 
承知しました！細かいところの指摘もろもろありがとうございます 😀

2020-06-08 13:15 UTC, piro0919 approved these changes
LGTM 👍

2020-06-09 00:24 UTC, merged